docs: Fix shell syntax issue in OpenShift guide
[ upstream commit e38b336e45d6f4c6b542957fe3816190bdd6d43f ]

This issue affects zsh users, for some reason bash doesn't
attempt to interpret the `.SecurityGroups[0].GroupId` expression,
while zsh does and it results in an error like this:

zsh: no matches found: .SecurityGroups[0].GroupId
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

Signed-off-by: Ilya Dmitrichenko <errordeveloper@gmail.com>
Signed-off-by: Robin Hahling <robin.hahling@gw-computing.net>
Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>